<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ValleyModkeeper</AssemblyName>
    <Product>Valley Modkeeper</Product>
    <AssemblyTitle>Valley Modkeeper</AssemblyTitle>
    <RootNamespace>TradutorModsStardew</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\app.ico" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    <Content Include="Assets\PixelifySans.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\PixelifySans-OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
